# Generated by Django 4.2.3 on 2023-07-07 19:10

from django.db import migrations, models
import fresh_basket.products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[fresh_basket.products.validators.validate_name_length])),
                ('description', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[fresh_basket.products.validators.validate_positive_price])),
                ('image', models.ImageField(upload_to='product_pics/', validators=[fresh_basket.products.validators.validate_file_size])),
            ],
        ),
    ]
