# Generated by Django 4.2.3 on 2023-07-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_weight',
            field=models.BooleanField(default=False),
        ),
    ]
