version: '3.8'

services:
  web:
    image: fresh_basket
    build: ./fresh_basket
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./fresh_basket/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./fresh_basket/.env
    volumes:
      - ./postgresql:/var/lib/postgresql/data