# Generated by Django 4.2.3 on 2023-08-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSimilarity',
        ),
    ]
