# Generated by Django 4.2.3 on 2023-07-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(),
        ),
    ]
