# Generated by Django 4.2.3 on 2023-07-09 09:47

from django.db import migrations, models
import fresh_basket.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_catalog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='catalog_image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_pics', validators=[fresh_basket.catalog.validators.validate_file_size]),
        ),
    ]
