# Generated by Django 4.2.3 on 2023-07-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
