# Generated by Django 4.2.3 on 2023-08-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0003_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='weight',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
